# Generated by Django 2.1.5 on 2019-01-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default=1, upload_to='img/tours'),
            preserve_default=False,
        ),
    ]
