# Generated by Django 2.1.5 on 2019-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20190121_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='slug',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
