# Generated by Django 2.1.5 on 2019-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20190123_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='summary',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
